# Generated by Django 3.2.7 on 2021-09-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tiene_igv',
            field=models.BooleanField(default=False),
        ),
    ]
