# Generated by Django 3.2.7 on 2021-09-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_item_tiene_igv'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'db_table': 'UNIDAD_MEDIDA',
            },
        ),
    ]
