# Generated by Django 3.2.7 on 2021-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_unidadmedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('ruc', models.CharField(db_column='RUC', max_length=13)),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': False,
            },
        ),
    ]
