# Generated by Django 3.2.7 on 2021-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=200)),
                ('sku', models.CharField(db_column='SKU', max_length=10)),
                ('precio', models.TextField(db_column='PRECIO')),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=200, null=True)),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('codigo', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('stock', models.IntegerField(db_column='STOCK')),
            ],
            options={
                'db_table': 'STOCK',
                'managed': False,
            },
        ),
    ]
